# ğŸš€ Genel Formatlama KurallarÄ± for nightly edition
#
# rustup run nightly cargo fmt
#
# ğŸš€ Genel Ayarlar
edition = "2024"                # Rust 2021 edition
max_width = 100                 # SatÄ±r uzunluÄŸu sÄ±nÄ±rÄ±
#use_small_heuristics = "Off"     # KÃ¼Ã§Ã¼k kod bloklarÄ±nÄ± tek satÄ±rda tutmaya Ã§alÄ±ÅŸ
#use_small_heuristics = "Default"     # KÃ¼Ã§Ã¼k kod bloklarÄ±nÄ± tek satÄ±rda tutmaya Ã§alÄ±ÅŸ
use_small_heuristics = "Max"     # KÃ¼Ã§Ã¼k kod bloklarÄ±nÄ± tek satÄ±rda tutmaya Ã§alÄ±ÅŸ
hard_tabs = false               # BoÅŸluk yerine tab kullanÄ±mÄ± (false: boÅŸluk)
tab_spaces = 4                  # Bir tab = 4 boÅŸluk

# ğŸ“Œ Fonksiyon ve Parametreler
#fn_params_layout = "Compressed"  # `fn_args_layout` yerine `fn_params_layout` kullanÄ±lmalÄ±
fn_params_layout = "Vertical"  # Place each function parameter on a new line if the line is too long
where_single_line = false        # `where` ifadelerini tek satÄ±ra sÄ±ÄŸdÄ±rma
#where_style = "Rfc"              # where rfcx
# ğŸ”— Import'larÄ± SÄ±ralama


# ğŸ¨ Kod DÃ¼zeni
reorder_impl_items = true        # `impl` iÃ§indeki Ã¶ÄŸeleri sÄ±ralÄ± hale getir
trailing_comma = "Never"      # Son satÄ±rlarda virgÃ¼l ekleme dÃ¼zeni
force_explicit_abi = true        # Harici fonksiyon Ã§aÄŸÄ±rmalarÄ±nda ABI belirt
wrap_comments = true             # Yorum satÄ±rlarÄ±nÄ± otomatik olarak satÄ±r sÄ±nÄ±rÄ±na gÃ¶re sar

# ğŸ— Struct ve Enumâ€™lar
struct_lit_width = 80            # Struct literal'lerinde satÄ±r geniÅŸliÄŸi limiti
struct_field_align_threshold = 0  # Struct alanlarÄ±nÄ± hizalama eÅŸiÄŸi
enum_discrim_align_threshold = 0  # Enum deÄŸerlerini hizalama eÅŸiÄŸi

#imports_granularity = "Crate"    # `use` ifadelerini crate bazÄ±nda grupla
imports_granularity = "Module"
group_imports = "StdExternalCrate"  # Import'larÄ± sÄ±ralÄ± hale getir
reorder_imports = true  # Import'larÄ± alfabetik olarak sÄ±rala